#!/bin/bash

# StoryGame Application Runner
# This script starts both frontend and backend servers using the current conda environment

# Terminal colors for better readability
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Define ports
BACKEND_PORT=11454
FRONTEND_PORT=3000

# # Define proxy settings (default to empty)
# HTTP_PROXY="http://127.0.0.1:49190"
# HTTPS_PROXY="http://127.0.0.1:49190"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --http-proxy=*)
      HTTP_PROXY="${1#*=}"
      shift
      ;;
    --https-proxy=*)
      HTTPS_PROXY="${1#*=}"
      shift
      ;;
    --help)
      echo "Usage: $0 [options]"
      echo "Options:"
      echo "  --http-proxy=URL    Set HTTP proxy URL (e.g. http://127.0.0.1:7890)"
      echo "  --https-proxy=URL   Set HTTPS proxy URL (e.g. http://127.0.0.1:7890)"
      echo "  --help              Show this help message"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Use --help for usage information"
      exit 1
      ;;
  esac
done

echo -e "${GREEN}Starting StoryGame Application...${NC}"
echo -e "${YELLOW}Using current conda environment${NC}"

# Display proxy settings if configured
if [[ -n "$HTTP_PROXY" ]]; then
  echo -e "${YELLOW}HTTP Proxy: $HTTP_PROXY${NC}"
fi
if [[ -n "$HTTPS_PROXY" ]]; then
  echo -e "${YELLOW}HTTPS Proxy: $HTTPS_PROXY${NC}"
fi

# Function to check if port is in use and kill the process
check_and_free_port() {
  local port=$1
  local port_info
  
  if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    port_info=$(lsof -i :$port -sTCP:LISTEN -t 2>/dev/null)
  else
    # Linux
    port_info=$(netstat -tuln | grep ":$port " | awk '{print $7}' 2>/dev/null)
  fi
  
  if [[ -n "$port_info" ]]; then
    echo -e "${YELLOW}Port $port is already in use. Attempting to free it...${NC}"
    if [[ "$OSTYPE" == "darwin"* ]]; then
      # macOS - kill the process directly
      kill -9 $port_info 2>/dev/null
    else
      # Linux - extract PID and kill
      local pid=$(echo $port_info | cut -d '/' -f 1)
      kill -9 $pid 2>/dev/null
    fi
    sleep 1
    echo -e "${GREEN}Port $port is now free.${NC}"
  fi
}

# Check if we're in a conda environment
if [ -z "$CONDA_DEFAULT_ENV" ]; then
  echo -e "${RED}Warning: No active conda environment detected.${NC}"
  echo -e "${YELLOW}It's recommended to activate your conda environment before running this script.${NC}"
  read -p "Continue anyway? (y/n) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
  fi
else
  echo -e "${GREEN}Active conda environment: $CONDA_DEFAULT_ENV${NC}"
fi

# Free ports if they are already in use
check_and_free_port $BACKEND_PORT
check_and_free_port $FRONTEND_PORT

# Function to check if a command exists
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

# Function to clean up processes when the script is terminated
cleanup() {
  echo -e "${YELLOW}Shutting down servers...${NC}"
  if [ ! -z "$BACKEND_PID" ]; then
    kill $BACKEND_PID 2>/dev/null
  fi
  if [ ! -z "$FRONTEND_PID" ]; then
    kill $FRONTEND_PID 2>/dev/null
  fi
  echo -e "${GREEN}Cleanup complete. Goodbye!${NC}"
  exit 0
}

# Set up cleanup on script termination
trap cleanup SIGINT SIGTERM

# Start Backend Server
echo -e "${GREEN}Starting backend server...${NC}"
cd backend || { echo -e "${RED}Error: backend directory not found${NC}"; exit 1; }
cd src || { echo -e "${RED}Error: src directory not found${NC}"; exit 1; }

# Set proxy environment variables for backend
if [[ -n "$HTTP_PROXY" ]]; then
  export HTTP_PROXY="$HTTP_PROXY"
  export http_proxy="$HTTP_PROXY"
fi
if [[ -n "$HTTPS_PROXY" ]]; then
  export HTTPS_PROXY="$HTTPS_PROXY"
  export https_proxy="$HTTPS_PROXY"
fi

python main.py &
BACKEND_PID=$!

# Check if backend started successfully
sleep 2
if ! ps -p $BACKEND_PID > /dev/null; then
  echo -e "${RED}Failed to start backend server${NC}"
  exit 1
fi

# Back to project root
cd ../../

# Start Frontend Server
echo -e "${GREEN}Starting frontend server...${NC}"
cd frontend || { echo -e "${RED}Error: frontend directory not found${NC}"; exit 1; }

# Create .env file with proxy settings if needed
if [[ -n "$HTTP_PROXY" || -n "$HTTPS_PROXY" ]]; then
  echo -e "${YELLOW}Setting up proxy for frontend...${NC}"
  echo "# Proxy settings generated by run_app.sh" > .env.development
  
  if [[ -n "$HTTP_PROXY" ]]; then
    echo "HTTP_PROXY=$HTTP_PROXY" >> .env.development
    echo "REACT_APP_HTTP_PROXY=$HTTP_PROXY" >> .env.development
  fi
  
  if [[ -n "$HTTPS_PROXY" ]]; then
    echo "HTTPS_PROXY=$HTTPS_PROXY" >> .env.development
    echo "REACT_APP_HTTPS_PROXY=$HTTPS_PROXY" >> .env.development
  fi
  
  echo -e "${GREEN}Frontend proxy settings saved to .env.development${NC}"
fi

# Check for npm or yarn
if command_exists yarn; then
  echo -e "${YELLOW}Starting NARRA-Gym with yarn...${NC}"
  yarn start &
  FRONTEND_PID=$!
elif command_exists npm; then
  echo -e "${YELLOW}Starting NARRA-Gym with npm...${NC}"
  npm start &
  FRONTEND_PID=$!
else
  echo -e "${RED}Error: Neither yarn nor npm found. Cannot start frontend.${NC}"
  cleanup
  exit 1
fi

# Return to the root directory
cd ..

# Wait for frontend to start and open browser
echo -e "${GREEN}Frontend will open in your browser shortly...${NC}"
echo -e "${GREEN}================================${NC}"
echo -e "${GREEN}StoryGame is now running!${NC}"
echo -e "${YELLOW}Frontend: http://localhost:$FRONTEND_PORT${NC}"
echo -e "${YELLOW}Backend: http://localhost:$BACKEND_PORT${NC}"
if [[ -n "$HTTP_PROXY" || -n "$HTTPS_PROXY" ]]; then
  echo -e "${YELLOW}Proxy settings are enabled${NC}"
fi
echo -e "${GREEN}================================${NC}"
echo -e "${YELLOW}Press Ctrl+C to stop both servers${NC}"

# Keep the script running until Ctrl+C
wait $BACKEND_PID $FRONTEND_PID 